### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by lubnafathima** [stuhli/awesome-event-ids#7]
Hey @stuhli 
To help people easily locate the ids
I can correct the alignment of the items in README.md
Kindly assign it to me.

**Comment by stuhli** [comment]
Hi,
sorry, I am not sure if I have understood you correctly? Can you please explain this a little more? Might be a good idea to provide a pull request to show what you mean. Even just as a draft, does not be complete for now.

**Comment by lubnafathima** [comment]
I have created a sample
Please check PR #8

**Comment by stuhli** [comment]
As mentioned in #8 feel free to contribute more PRs. For the time being I'm gonna close this issue.
